apiVersion: v1
kind: Pod
metadata:
  namespace: lesson8
  labels:
    app: nginx
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: lesson8
  name: nginx-svc
spec:
  ports:
    - name: netology-web
      port: 80
  selector:
    app: nginx
