apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: netology-web
spec:
  containers:
    - name: echoserver
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  ports:
    - name: netology-web
      port: 8080
  selector:
    app: web
