all:
    hosts:
        node1:
        
            ansible_host: 158.160.63.22
            ip: 10.0.1.24
            access_ip: 158.160.63.22
        
        
        node2:
            ansible_host: 158.160.112.126
            ip: 10.0.1.25
            access_ip: 158.160.112.126
        
        node3:
            ansible_host: 51.250.69.228
            ip: 10.0.1.21
            access_ip: 51.250.69.228
        
        node4:
            ansible_host: 158.160.120.202
            ip: 10.0.1.16
            access_ip: 158.160.120.202
        
        node5:
            ansible_host: 158.160.122.32
            ip: 10.0.1.32
            access_ip: 158.160.122.32
        
    children:
        kube_control_plane:
            hosts:
                node1:
        kube_node:
            hosts:
                node2:
                node3:
                node4:
                node5:
        etcd:
            hosts:
                node1:
        k8s_cluster:
            children:
                kube_control_plane:
                kube_node:
        calico_rr:
            hosts: {}