all:
    hosts:
        node1:
        
            ansible_host: 51.250.6.182
            ip: 10.0.1.8
            access_ip: 51.250.6.182
        
        
        node2:
            ansible_host: 62.84.113.241
            ip: 10.0.1.25
            access_ip: 62.84.113.241
        
        node3:
            ansible_host: 51.250.3.107
            ip: 10.0.1.29
            access_ip: 51.250.3.107
        
    children:
        kube_control_plane:
            hosts:
                node1:
        kube_node:
            hosts:
                node2:
                node3:
                node4:
                node5:
        etcd:
            hosts:
                node1:
        k8s_cluster:
            children:
                kube_control_plane:
                kube_node:
        calico_rr:
            hosts: {}