all:
    hosts:
        node1:
        
            ansible_host: 51.250.81.85
            ip: 10.0.1.36
            access_ip: 51.250.81.85
        
        
        node2:
            ansible_host: 158.160.58.105
            ip: 10.0.1.28
            access_ip: 158.160.58.105
        
        node3:
            ansible_host: 158.160.111.230
            ip: 10.0.1.5
            access_ip: 158.160.111.230
        
        node4:
            ansible_host: 158.160.59.58
            ip: 10.0.1.12
            access_ip: 158.160.59.58
        
        node5:
            ansible_host: 84.201.156.244
            ip: 10.0.1.33
            access_ip: 84.201.156.244
        
    children:
        kube_control_plane:
            hosts:
                node1:
        kube_node:
            hosts:
                node2:
                node3:
                node4:
                node5:
        etcd:
            hosts:
                node1:
        k8s_cluster:
            children:
                kube_control_plane:
                kube_node:
        calico_rr:
            hosts: {}