apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: myapp
  ports:
    - name: nginx-svc
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-svc
      protocol: TCP
      port: 9002
      targetPort: 8080
