---
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  selector:
    app: myapp
  ports:
    - name: nginx-web
      protocol: TCP
      port: 80
      nodePort: 30080
    - name: multitool-web
      protocol: TCP
      port: 8080
      nodePort: 30081
  type: NodePort
